---
title: "new_mp4"
author: "Aoi, Ester"
date: "4/30/2018"
output: html_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
```


```{r, message = FALSE, warning = FALSE, echo = TRUE}
#gross 2007
gross_2007 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2007;")

#gross data
gross_2007 <- gross_2007 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2007 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2007;") 

#budget data
budget_2007 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2007;")

budget_2007 <- budget_2007 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2007 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2007;")

s1_2007 <- left_join(genre_2007, gross_2007, by = "id") 

s2_2007 <- left_join(s1_2007, budget_2007, by = "id")

sum_2007 <- left_join(s2_2007, rating_2007, by = "id")

sum_2007 <- na.omit(sum_2007)

sum_2007_2 <- sum_2007 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(5)

# just 5 since they're 5 movies in oscar data



sum_genre2007 <- sum_2007 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(17) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2008
gross_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2008;")

#gross data
gross_2008 <- gross_2008 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2008;") 

#budget data
budget_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2008;")

budget_2008 <- budget_2008 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2008;")

s1_2008 <- left_join(genre_2008, gross_2008, by = "id") 

s2_2008 <- left_join(s1_2008, budget_2008, by = "id")

sum_2008 <- left_join(s2_2008, rating_2008, by = "id")

sum_2008 <- na.omit(sum_2008)

sum_2008_2 <- sum_2008 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(5)

# just 5 since they're 5 movies in oscar data

sum_genre2008 <- sum_2008 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(20) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2009
gross_2009<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2009;")

#gross data
gross_2009 <- gross_2009 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2009;") 

#budget data
budget_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2009;")

budget_2009 <- budget_2009 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2009;")

s1_2009 <- left_join(genre_2009, gross_2009, by = "id") 

s2_2009 <- left_join(s1_2009, budget_2009, by = "id")

sum_2009 <- left_join(s2_2009, rating_2009, by = "id")

sum_2009 <- na.omit(sum_2009)

sum_2009_2 <- sum_2009 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(10)

# just 10 since they're 10 movies in oscar data



sum_genre2009 <- sum_2009 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(37) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))


```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2010
gross_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2010;")

#gross data
gross_2010 <- gross_2010 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2010;") 

#budget data
budget_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2010;")

budget_2010 <- budget_2010 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2010;")

s1_2010 <- left_join(genre_2010, gross_2010, by = "id") 

s2_2010 <- left_join(s1_2010, budget_2010, by = "id")

sum_2010 <- left_join(s2_2010, rating_2010, by = "id")

sum_2010 <- na.omit(sum_2010)

sum_2010_2 <- sum_2010 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(9)

# just 9 since they're 9 movies in oscar data

sum_genre2010 <- sum_2010 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(40) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2011
gross_2011<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2011;")

#gross data
gross_2011 <- gross_2011 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2011;") 

#budget data
budget_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2011;")

budget_2011 <- budget_2011 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2011;")

s1_2011 <- left_join(genre_2011, gross_2011, by = "id") 

s2_2011 <- left_join(s1_2011, budget_2011, by = "id")

sum_2011 <- left_join(s2_2011, rating_2011, by = "id")

sum_2011 <- na.omit(sum_2011)

sum_2011_2 <- sum_2011 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(9)

# just 9 since they're 9 movies in oscar data

sum_genre2011 <- sum_2011 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(27) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2012
gross_2012<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2012;")

#gross data
gross_2012 <- gross_2012 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2012;") 

#budget data
budget_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2012;")

budget_2012 <- budget_2012 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2012;")

s1_2012 <- left_join(genre_2012, gross_2012, by = "id") 

s2_2012 <- left_join(s1_2012, budget_2012, by = "id")

sum_2012 <- left_join(s2_2012, rating_2012, by = "id")

sum_2012 <- na.omit(sum_2012)

sum_2012_2 <- sum_2012 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info, budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(9)

# just 9 since they're 8 movies in oscar data



sum_genre2012 <- sum_2012 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross))%>%
  head(29) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2013
gross_2013<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2013;")

#gross data
gross_2013 <- gross_2013 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2013;") 

#budget data
budget_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2013;")

budget_2013 <- budget_2013 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))
 
rating_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2013;")

s1_2013 <- left_join(genre_2013, gross_2013, by = "id") 

s2_2013 <- left_join(s1_2013, budget_2013, by = "id")

sum_2013 <- left_join(s2_2013, rating_2013, by = "id")

sum_2013 <- na.omit(sum_2013)

sum_2013_2 <- sum_2013 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(9)

# just 9 since they're 8 movies in oscar data



sum_genre2013 <- sum_2013 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(36) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2014
gross_2014<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2014;")

#gross data
gross_2014 <- gross_2014 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2014;") 

#budget data
budget_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2014;")

budget_2014 <- budget_2014 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))

rating_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2014;")

s1_2014 <- left_join(genre_2014, gross_2014, by = "id") 

s2_2014 <- left_join(s1_2014, budget_2014, by = "id")

sum_2014 <- left_join(s2_2014, rating_2014, by = "id")

sum_2014 <- na.omit(sum_2014)

sum_2014_2 <- sum_2014 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(8)

# just 8 since they're 8 movies in oscar data


sum_genre2014 <- sum_2014 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(29) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2015
# add genre of movie
gross_2015<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2015;")

#gross data
gross_2015 <- gross_2015 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

#genre data
genre_2015 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2015;") 

#budget data
budget_2015 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2015;")

budget_2015 <- budget_2015 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))

rating_2015 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2015;")

s1_2015 <- left_join(genre_2015, gross_2015, by = "id") 

s2_2015 <- left_join(s1_2015, budget_2015, by = "id")

sum_2015 <- left_join(s2_2015, rating_2015, by = "id")

sum_2015 <- na.omit(sum_2015)

sum_2015_2 <- sum_2015 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id, title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(8)

# just 8 since they're 8 movies in oscar data


sum_genre2015 <- sum_2015 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(34) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#gross 2016
# add genre of movie
gross_2016<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND production_year = 2016;")

gross_2016 <- gross_2016 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

genre_2016 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND production_year = 2016;") 

budget_2016 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS budget_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 105 
AND production_year = 2016;")

budget_2016 <- budget_2016 %>%
  mutate(budget_string = str_extract(budget_info, "^\\$[0-9,]+"),
         budget = parse_number(budget_string)) %>%
  arrange(desc(budget))

rating_2016 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101
AND production_year = 2016;")

s1_2016 <- left_join(genre_2016, gross_2016, by = "id") 

s2_2016 <- left_join(s1_2016, budget_2016, by = "id")

sum_2016 <- left_join(s2_2016, rating_2016, by = "id")

sum_2016 <- na.omit(sum_2016)

sum_2016_2 <- sum_2016 %>% 
  select(id, title.x, genre_info, gross, budget, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info,budget) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
  mutate(earning = sum_gross - budget) %>%
arrange(desc(sum_gross)) %>%
  head(9)
# just 9 since they're 9 movies in oscar data

sum_genre2016 <- sum_2016 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  head(35) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
f1 <- bind_rows(sum_genre2007, sum_genre2008)

f2 <- bind_rows(f1, sum_genre2009)
f3 <- bind_rows(f2, sum_genre2010)
f4 <- bind_rows(f3, sum_genre2011)
f5 <- bind_rows(f4, sum_genre2012)
f6 <- bind_rows(f5, sum_genre2013)
f7 <- bind_rows(f6, sum_genre2014)
f8 <- bind_rows(f7, sum_genre2015)

all_film <- bind_rows(f8, sum_genre2016)

# add id to separate oscar or sum 

ggplot(all_film, aes(x = production_year, y = genre, color = genre_info)) + 
  geom_point() +
  geom_line() + 
  labs(x = "Production Year", y = "Total Number") +
  scale_fill_discrete(name = "Genre")

```

```{r,message = FALSE, warning = FALSE, echo= TRUE}
s1 <- bind_rows(sum_2007_2, sum_2008_2)

s2 <- bind_rows(s1, sum_2009_2)
s3 <- bind_rows(s2, sum_2010_2)
s4 <- bind_rows(s3, sum_2011_2)
s5 <- bind_rows(s4, sum_2012_2)
s6 <- bind_rows(s5, sum_2013_2)
s7 <- bind_rows(s6, sum_2014_2)
s8 <- bind_rows(s7, sum_2015_2)

sum_film <- bind_rows(s8, sum_2016_2)

```




```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2008 Best picture nominees
oscar_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'No Country for Old Men' 
OR title = 'Atonement' 
OR title = 'Juno' 
OR title = 'Michael Clayton' 
OR title = 'There Will Be Blood');")

oscar_2008 <- oscar_2008 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2008 <- na.omit(oscar_2008)

os_genre_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'No Country for Old Men' 
OR title = 'Atonement' 
OR title = 'Juno' 
OR title = 'Michael Clayton' 
OR title = 'There Will Be Blood');")


rt_oscar_2008 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'No Country for Old Men' 
OR title = 'Atonement' 
OR title = 'Juno' 
OR title = 'Michael Clayton' 
OR title = 'There Will Be Blood');")

os1_sum_2008 <- left_join(os_genre_2008, oscar_2008, by = "id") 

os_sum_2008 <- left_join(os1_sum_2008, rt_oscar_2008, by = "id")

os_sum_2008 <- na.omit(os_sum_2008)

sum_oscar_2008 <- os_sum_2008 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross))

sum_os_genre2008 <- os_sum_2008 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2009 Best picture nominees
oscar_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'Slumdog Millionaire' 
OR title = 'The Curious Case of Benjamin Button' 
OR title = 'Frost/Nixon' 
OR title = 'Milk' 
OR title = 'The Reader');")

oscar_2009 <- oscar_2009 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2009 <- na.omit(oscar_2009)

os_genre_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'Slumdog Millionaire' 
OR title = 'The Curious Case of Benjamin Button' 
OR title = 'Frost/Nixon' 
OR title = 'Milk' 
OR title = 'The Reader');")

rt_oscar_2009 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'Slumdog Millionaire' 
OR title = 'The Curious Case of Benjamin Button' 
OR title = 'Frost/Nixon' 
OR title = 'Milk' 
OR title = 'The Reader');")

os1_sum_2009 <- left_join(os_genre_2009, oscar_2009, by = "id") 

os_sum_2009 <- left_join(os1_sum_2009, rt_oscar_2009, by = "id")

os_sum_2009 <- na.omit(os_sum_2009)

sum_oscar_2009 <- os_sum_2009 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2009 <- os_sum_2009 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2010 Best picture nominees
oscar_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'The Hurt Locker' 
OR title = 'Avatar' 
OR title = 'The Blind Side' 
OR title = 'District 9' 
OR title = 'An Education' 
OR title = 'Inglourious Basterds' 
OR title = 'Precious' 
OR title = 'A Serious Man' 
OR title = 'Up'
OR title = 'Up in the Air');")

oscar_2010 <- oscar_2010 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2010 <- na.omit(oscar_2010)

os_genre_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'The Hurt Locker' 
OR title = 'Avatar' 
OR title = 'The Blind Side' 
OR title = 'District 9' 
OR title = 'An Education' 
OR title = 'Inglourious Basterds' 
OR title = 'Precious' 
OR title = 'A Serious Man' 
OR title = 'Up'
OR title = 'Up in the Air');")


rt_oscar_2010 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'The Hurt Locker' 
OR title = 'Avatar' 
OR title = 'The Blind Side' 
OR title = 'District 9' 
OR title = 'An Education' 
OR title = 'Inglourious Basterds' 
OR title = 'Precious' 
OR title = 'A Serious Man' 
OR title = 'Up'
OR title = 'Up in the Air');")

os1_sum_2010 <- left_join(os_genre_2010, oscar_2010, by = "id") 

os_sum_2010 <- left_join(os1_sum_2010, rt_oscar_2010, by = "id")

os_sum_2010 <- na.omit(os_sum_2010)

sum_oscar_2010 <- os_sum_2010 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2010 <- os_sum_2010 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2011 Best picture nominees
oscar_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'The King''s Speech' 
OR title = 'Black Swan' 
OR title = 'The Fighter' 
OR title = 'Inception' 
OR title = '127 Hours' 
OR title = 'The Social Network' 
OR title = 'Toy Story 3' 
OR title = 'True Grit' 
OR title = 'Winter''s Bone')
AND production_year = 2010;")

oscar_2011 <- oscar_2011 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2011 <- na.omit(oscar_2011)

os_genre_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'The King''s Speech' 
OR title = 'Black Swan' 
OR title = 'The Fighter' 
OR title = 'Inception' 
OR title = '127 Hours' 
OR title = 'The Social Network' 
OR title = 'Toy Story 3' 
OR title = 'True Grit' 
OR title = 'Winter''s Bone');")

rt_oscar_2011 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'The King''s Speech' 
OR title = 'Black Swan' 
OR title = 'The Fighter' 
OR title = 'Inception' 
OR title = '127 Hours' 
OR title = 'The Social Network' 
OR title = 'Toy Story 3' 
OR title = 'True Grit' 
OR title = 'Winter''s Bone');")

os1_sum_2011 <- left_join(os_genre_2011, oscar_2011, by = "id") 

os_sum_2011 <- left_join(os1_sum_2011, rt_oscar_2011, by = "id")

os_sum_2011 <- na.omit(os_sum_2011)

sum_oscar_2011 <- os_sum_2011 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2011 <- os_sum_2011 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2012 Best picture nominees
oscar_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'The Artist' 
OR title = 'The Descendants' 
OR title = 'Extremely Loud & Incredibly Close' 
OR title = 'The Help' 
OR title = 'Hugo' 
OR title = 'Midnight in Paris' 
OR title = 'Moneyball' 
OR title = 'The Tree of Life' 
OR title = 'War Horse');")

oscar_2012 <- oscar_2012 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2012 <- na.omit(oscar_2012)

os_genre_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'The Artist' 
OR title = 'The Descendants' 
OR title = 'Extremely Loud & Incredibly Close' 
OR title = 'The Help' 
OR title = 'Hugo' 
OR title = 'Midnight in Paris' 
OR title = 'Moneyball' 
OR title = 'The Tree of Life' 
OR title = 'War Horse');")


rt_oscar_2012 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'The Artist' 
OR title = 'The Descendants' 
OR title = 'Extremely Loud & Incredibly Close' 
OR title = 'The Help' 
OR title = 'Hugo' 
OR title = 'Midnight in Paris' 
OR title = 'Moneyball' 
OR title = 'The Tree of Life' 
OR title = 'War Horse');")

os1_sum_2012 <- left_join(os_genre_2012, oscar_2012, by = "id") 

os_sum_2012 <- left_join(os1_sum_2012, rt_oscar_2012, by = "id")

os_sum_2012 <- na.omit(os_sum_2012)

sum_oscar_2012 <- os_sum_2012 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2012 <- os_sum_2012 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2013 Best picture nominees
oscar_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'Argo' 
OR title = 'Amour' 
OR title = 'Beasts of the Southern Wild' 
OR title = 'Django Unchained' 
OR title = 'Les Misérables' 
OR title = 'Life of Pi' 
OR title = 'Lincoln' 
OR title = 'Silver Linings Playbook' 
OR title = 'Zero Dark Thirty')
AND production_year = 2012;")


oscar_2013 <- oscar_2013 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2013 <- na.omit(oscar_2013)


os_genre_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'Argo' 
OR title = 'Amour' 
OR title = 'Beasts of the Southern Wild' 
OR title = 'Django Unchained' 
OR title = 'Les Misérables' 
OR title = 'Life of Pi' 
OR title = 'Lincoln' 
OR title = 'Silver Linings Playbook' 
OR title = 'Zero Dark Thirty');")


rt_oscar_2013 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'Argo' 
OR title = 'Amour' 
OR title = 'Beasts of the Southern Wild' 
OR title = 'Django Unchained' 
OR title = 'Les Misérables' 
OR title = 'Life of Pi' 
OR title = 'Lincoln' 
OR title = 'Silver Linings Playbook' 
OR title = 'Zero Dark Thirty');")

os1_sum_2013 <- left_join(os_genre_2013, oscar_2013, by = "id") 

os_sum_2013 <- left_join(os1_sum_2013, rt_oscar_2013, by = "id")

os_sum_2013 <- na.omit(os_sum_2013)

sum_oscar_2013 <- os_sum_2013 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2013 <- os_sum_2013 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2014 Best picture nominees
oscar_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = '12 Years a Slave' 
OR title = 'American Hustle' 
OR title = 'Captain Phillips' 
OR title = 'Dallas Buyers Club' 
OR title = 'Gravity' 
OR title = 'Her' 
OR title = 'Nebraska' 
OR title = 'Philomena' 
OR title = 'The Wolf of Wall Street')
AND production_year = 2013;")

oscar_2014 <- oscar_2014 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2014 <- na.omit(oscar_2014)

os_genre_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = '12 Years a Slave' 
OR title = 'American Hustle' 
OR title = 'Captain Phillips' 
OR title = 'Dallas Buyers Club' 
OR title = 'Gravity' 
OR title = 'Her' 
OR title = 'Nebraska' 
OR title = 'Philomena' 
OR title = 'The Wolf of Wall Street');")

rt_oscar_2014 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = '12 Years a Slave' 
OR title = 'American Hustle' 
OR title = 'Captain Phillips' 
OR title = 'Dallas Buyers Club' 
OR title = 'Gravity' 
OR title = 'Her' 
OR title = 'Nebraska' 
OR title = 'Philomena' 
OR title = 'The Wolf of Wall Street');")

os1_sum_2014 <- left_join(os_genre_2014, oscar_2014, by = "id") 

os_sum_2014 <- left_join(os1_sum_2014, rt_oscar_2014, by = "id")

os_sum_2014 <- na.omit(os_sum_2014)

sum_oscar_2014 <- os_sum_2014 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2014 <- os_sum_2014 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2015 Best picture nominees
oscar_2015<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'Birdman or (The Unexpected Virtue of Ignorance)' 
OR title = 'American Sniper' 
OR title = 'Boyhood' 
OR title = 'The Grand Budapest Hotel' 
OR title = 'The Imitation Game' 
OR title = 'Selma' 
OR title = 'The Theory of Everything' 
OR title = 'Whiplash' );")

oscar_2015 <- oscar_2015 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2015 <- na.omit(oscar_2015)

os_genre_2015<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'Birdman or (The Unexpected Virtue of Ignorance)' 
OR title = 'American Sniper' 
OR title = 'Boyhood' 
OR title = 'The Grand Budapest Hotel' 
OR title = 'The Imitation Game' 
OR title = 'Selma' 
OR title = 'The Theory of Everything' 
OR title = 'Whiplash' );")


rt_oscar_2015<- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'Birdman or (The Unexpected Virtue of Ignorance)' 
OR title = 'American Sniper' 
OR title = 'Boyhood' 
OR title = 'The Grand Budapest Hotel' 
OR title = 'The Imitation Game' 
OR title = 'Selma' 
OR title = 'The Theory of Everything' 
OR title = 'Whiplash' );")

os1_sum_2015 <- left_join(os_genre_2015, oscar_2015, by = "id") 

os_sum_2015 <- left_join(os1_sum_2015, rt_oscar_2015, by = "id")

os_sum_2015 <- na.omit(os_sum_2015)

sum_oscar_2015 <- os_sum_2015 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2015 <- os_sum_2015 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))

```



```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2016 Best picture nominees
oscar_2016<- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'The Big Short' 
OR title = 'Bridge of Spies' 
OR title = 'Brooklyn' 
OR title = 'Mad Max: Fury Road' 
OR title = 'The Revenant' 
OR title = 'The Martian' 
OR title = 'Room' 
OR title = 'Spotlight' );")

oscar_2016 <- oscar_2016 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))
oscar_2016 <- na.omit(oscar_2016)

os_genre_2016 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'The Big Short' 
OR title = 'Bridge of Spies' 
OR title = 'Brooklyn' 
OR title = 'Mad Max: Fury Road' 
OR title = 'The Revenant' 
OR title = 'The Martian' 
OR title = 'Room' 
OR title = 'Spotlight');") 

rt_oscar_2016 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'The Big Short' 
OR title = 'Bridge of Spies' 
OR title = 'Brooklyn' 
OR title = 'Mad Max: Fury Road' 
OR title = 'The Revenant' 
OR title = 'The Martian' 
OR title = 'Room' 
OR title = 'Spotlight');") 

os1_sum_2016 <- left_join(os_genre_2016, oscar_2016, by = "id") 

os_sum_2016 <- left_join(os1_sum_2016, rt_oscar_2016, by = "id")

os_sum_2016 <- na.omit(os_sum_2016)

sum_oscar_2016 <- os_sum_2016 %>% select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross))

sum_os_genre2016 <- os_sum_2016 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info, production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))


```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
#Oscar 2017 Best picture nominees
oscar_2017 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS gross_info, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 107 
AND (title = 'Arrival' 
OR title = 'Fences' 
OR title = 'Hacksaw Ridge' 
OR title = 'Hell or High Water' 
OR title = 'Hidden Figures' 
OR title = 'La La Land' 
OR  title = 'Lion' 
OR title = 'Manchester by the Sea' 
OR title = 'Moonlight');")

oscar_2017 <- oscar_2017 %>%
  mutate(gross_string = str_extract(gross_info, "^\\$[0-9,]+"),
         gross = parse_number(gross_string)) %>%
  arrange(desc(gross))

os_genre_2017 <- dbGetQuery(db, "SELECT t.id, t.title, mi.info AS genre_info
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE mi.info_type_id = 3 
AND (title = 'Arrival' 
OR title = 'Fences' 
OR title = 'Hacksaw Ridge' 
OR title = 'Hell or High Water' 
OR title = 'Hidden Figures' 
OR title = 'La La Land' 
OR  title = 'Lion' 
OR title = 'Manchester by the Sea' 
OR title = 'Moonlight');")



os_rating_2017 <- dbGetQuery(db, "SELECT t.id, t.title, mii.info AS rating_info
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
WHERE mii.info_type_id = 101 
AND (title = 'Arrival' 
OR title = 'Fences' 
OR title = 'Hacksaw Ridge' 
OR title = 'Hell or High Water' 
OR title = 'Hidden Figures' 
OR title = 'La La Land' 
OR  title = 'Lion' 
OR title = 'Manchester by the Sea' 
OR title = 'Moonlight');")


os1_sum_2017 <- left_join(os_genre_2017, oscar_2017, by = "id")

os_sum_2017 <- left_join(os1_sum_2017, os_rating_2017, by = "id")

os_sum_2017 <- na.omit(os_sum_2017)

sum_oscar_2017 <- os_sum_2017 %>% 
  select(id, title.x, genre_info, gross, production_year, rating_info) %>%
group_by(id,title.x, production_year, rating_info) %>%
summarise(sum_gross = max(gross), genre = paste(unique(genre_info), collapse=', ')) %>%
arrange(desc(sum_gross)) 

sum_os_genre2017 <- os_sum_2017 %>%
  select(id, title.x, genre_info, gross, production_year) %>%
  group_by(id,title.x, genre_info, production_year) %>%
  summarise(sum_gross = max(gross)) %>%
  arrange(desc(sum_gross)) %>%
  group_by(genre_info,production_year) %>%
  summarise(genre = sum(n_distinct(title.x)))
```


```{r, message = FALSE, warning = FALSE, echo= TRUE}
os1 <- bind_rows(sum_os_genre2008, sum_os_genre2009)
os2 <- bind_rows(os1,sum_os_genre2010)
os3 <- bind_rows(os2,sum_os_genre2011)
os4 <- bind_rows(os3,sum_os_genre2012)
os5 <- bind_rows(os4,sum_os_genre2013)
os6 <- bind_rows(os5,sum_os_genre2014)
os7 <- bind_rows(os6,sum_os_genre2015)
os8 <- bind_rows(os7,sum_os_genre2016)
all_oscar <- bind_rows(os8,sum_os_genre2017)

sum1 <- bind_rows(sum_oscar_2008, sum_oscar_2009)
sum2 <- bind_rows(sum1, sum_oscar_2010)
sum3 <- bind_rows(sum2, sum_oscar_2011)
sum4 <- bind_rows(sum3, sum_oscar_2012)
sum5 <- bind_rows(sum4, sum_oscar_2013)
sum6 <- bind_rows(sum5, sum_oscar_2014)
sum7 <- bind_rows(sum6, sum_oscar_2015)
sum8 <- bind_rows(sum7, sum_oscar_2016)

sum_oscar <- bind_rows(sum8, sum_oscar_2017)

ggplot(sum_oscar, aes(x = sum_gross, y = rating_info, color = as.factor(production_year))) + 
  geom_point() 

ggplot(all_oscar, aes(x = production_year, y = genre, color = genre_info)) + 
  geom_point() +
  geom_line()
```

```{r, message = FALSE, warning = FALSE, echo= TRUE}
all_oscar$oscar <- "TRUE"
all_film$oscar <- "FALSE"

data_all <- bind_rows(all_oscar, all_film)

ggplot(data_all) + 
  geom_bar(aes(x = genre_info, y = genre, fill = oscar), stat = "identity", position = "stack") +
  labs(y = "Total Number", x = "Genre") +
  scale_fill_discrete(name = "Is It an Oscar Movie?", breaks = c("FALSE", "TRUE"), labels = c("No", "Yes"))
```




```{r, message = FALSE, warning = FALSE, echo= TRUE}
data_sum
# gross vs rating
#cgange the rating scale 
ggplot(data_sum, aes(x = rating_info, y = sum_gross, color = oscar)) + 
  geom_point() +
  labs(x = "Rating", y = "Total Gross") +
  scale_fill_discrete(name = "Is It an Oscar Movie?", breaks = c("FALSE", "TRUE"), labels = c("No", "Yes"))
```



https://github.com/aogawa-4/mp4.git [^1]
http://graphics.latimes.com/oscars-2016-voters/ [^2]
http://www.vulture.com/2017/11/when-will-marvel-studios-win-an-oscar.html [^3]

[^1]: Github link for our project
[^2]: Source for article "Oscars 2016 voters"
[^3]: Source for article "When Will Marvel Studios Win an Oscar?"
